# ナッシュ均衡をnashpyで見つける

対応する動画：[ゲーム理論・進化ゲーム②　ナッシュ均衡　実装編【研究で使うPython #45】](https://youtu.be/OWFsvbupgrY)

動画のプレイリスト：[研究で使うPython](https://www.youtube.com/playlist?list=PLw5AEs-T7pLHxLaNvGD9tnhrDxAgH-QIw)

## nashpyのインストール（初回のみ）

In [1]:
!pip install nashpy

## 必要モジュールのimport

In [2]:
import nashpy as nash
import numpy as np

## ゲームの定義

In [3]:
A = np.array([[4,3],[5,2]]) # A is the row player
B = np.array([[5,6],[4,3]]) # B is the column player
game1 = nash.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[4 3]
 [5 2]]

Column player:
[[5 6]
 [4 3]]

## ナッシュ均衡を求める

In [4]:
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([0., 1.]))
(array([0., 1.]), array([1., 0.]))
(array([0.5, 0.5]), array([0.5, 0.5]))


## 囚人のジレンマゲームのナッシュ均衡を求める

In [5]:
A = np.array([[3,0],[5,1]]) # A is the row player
B = np.array([[3,5],[0,1]]) # B is the column player
prisoners_dilemma = nash.Game(A,B)
prisoners_dilemma

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [5 1]]

Column player:
[[3 5]
 [0 1]]

In [6]:
equilibria = prisoners_dilemma.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([0., 1.]))
