# NumPy配列入門

対応する動画：[NumPy配列入門　①基礎【研究で使うPython51】](https://youtu.be/w64TRDkZhu8)

動画のプレイリスト：[研究で使うPython](https://www.youtube.com/playlist?list=PLw5AEs-T7pLHxLaNvGD9tnhrDxAgH-QIw)

In [3]:
import numpy as np

## リストとの違い

In [4]:
a = [1, 2, 3]
b = [4, 5, 6]

print(a * b)

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b)

[ 4 10 18]


## 基礎

In [6]:
# 1次元配列
a = np.array([1, 2, 3, 4, 5])
print(a)

# 2次元配列
b = np.array([[10, 9, 8],[7, 6, 5]])
print(b)

[1 2 3 4 5]
[[10  9  8]
 [ 7  6  5]]


In [7]:
# 次元取得
print(a.ndim)
print(b.ndim)

1
2


In [8]:
a = np.array([[1,2,3,4],[5,6,7,8]])

print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(a[1,3]) # 1行3列目の要素（0から数えて）

8


In [10]:
print(a[0,:]) # 0行目
print(a[:,1]) # 1列目

[1 2 3 4]
[2 6]


In [11]:
b = np.array([[1,2,3,4,5,6,7,8,9],[0,0,0,0,0,0,0,0,0]])
print(b)
print(b[0,1:8:2]) # 0行目、1～7列（間隔2）

[[1 2 3 4 5 6 7 8 9]
 [0 0 0 0 0 0 0 0 0]]
[2 4 6 8]


## 初期化

In [12]:
# 0で初期化
print(np.zeros((2,4))) # 2行4列

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# 1で初期化
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# その他の数字で初期化
print(np.full((2,4),5))

[[5 5 5 5]
 [5 5 5 5]]


In [17]:
# 0.0以上、1.0未満の乱数で初期化
print(np.random.rand(2,4))

[[0.56246909 0.61776793 0.27956305 0.39847829]
 [0.95178958 0.27304361 0.82435759 0.30277672]]


In [20]:
# 整数の乱数で初期化
print(np.random.randint(5,10,size=(2,6))) # 5以上10未満の乱数で2行6列の行列を初期化

[[5 7 6 5 9 6]
 [9 9 6 7 9 5]]


In [21]:
# 一部を変更
a = np.zeros((5,5))
print(a,end='\n \n')

b = np.ones((3,3))

a[1:4,1:4] = b # aの1～3行、1～3列にbを挿入
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# コピーの注意
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a) # 同じ配列を参照しているのでaも変更されてしまう

a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a) # aの方は変更されていない

[100   2   3]
[100   2   3]
[100   2   3]
[1 2 3]
