# NumPy配列入門　②計算

対応する動画：[NumPy配列入門　②計算【研究で使うPython #52】](https://youtu.be/QTgx7QcVs3M)

動画のプレイリスト：[研究で使うPython](https://www.youtube.com/playlist?list=PLw5AEs-T7pLHxLaNvGD9tnhrDxAgH-QIw)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a+2)

[3 4 5 6]


In [3]:
print(a-1)

[0 1 2 3]


In [4]:
print(a*3)

[ 3  6  9 12]


In [5]:
print(a/2)

[0.5 1.  1.5 2. ]


In [6]:
b = np.array([3,2,1,0])
print(a+b)

[4 4 4 4]


In [7]:
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


## 線形代数

### 行列の積

In [8]:
a = np.array([[1,2],[3,4]])
b = np.full((2,2), 2)
print(a)
print(b)

print(np.dot(a, b))

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[ 6  6]
 [14 14]]


### 逆行列

In [9]:
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


### 行列式

In [10]:
a = np.array([[0, 1], [2, 3]])
print(a)
print(np.linalg.det(a))

b = np.identity(3)
print(b)
print(np.linalg.det(b))

[[0 1]
 [2 3]]
-2.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


### 固有値と固有ベクトル

In [11]:
a = np.array([[3, 1],[2, 4]])

# a_eig[0]に固有値、a_eig[1]に固有ベクトルが格納される
a_eig = np.linalg.eig(a)

# 固有値を表示
print(a_eig[0])

# 固有ベクトルを表示
print(a_eig[1])

[2. 5.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


## 基本統計量

In [12]:
a = a = np.array([[1,2,3],[4,5,6]])

In [13]:
print(np.mean(a)) # 平均
print(np.min(a))  # 最小値
print(np.max(a))  # 最大値
print(np.sum(a))  # 合計
print(np.std(a))  # 標準偏差
print(np.var(a))  # 分散

3.5
1
6
21
1.707825127659933
2.9166666666666665


## その他

### ファイル読み込み

In [14]:
f = np.genfromtxt('data.txt', delimiter=',')
print(f)

[ 1. 10. 20. 30. 40. 50.]


In [15]:
print(f > 20)

[False False False  True  True  True]


In [16]:
print(f[f>20])

[30. 40. 50.]
